<?xml version="1.0"?>
<package format="3">
  <name>magician_body_pose_estimation</name>
  <version>0.0.1</version>
  <description>ROS wxPython wrapper for 3D body easy rosrun/roslaunch usage.</description>

  <maintainer email="ammarkov@ics.forth.gr">Ammar Qammaz</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <exec_depend>python3</exec_depend>

  <export/>
</package>
